# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				sheep = true
				pig = true
				cow = true
				chicken = true
				minecart = true
				tnt_minecart = true
				furnace_minecart = true
				glow_squid = true
				armor_stand = true
				bat = true
				squid = true
				spider = true
				creeper = true
				skeleton = true
				cod = true
				enderman = true
				zombie = true
				cave_spider = true
				dolphin = true
				bee = true
				item = true
				slime = true
				drowned = true
				arrow = true
				experience_orb = true
				zombie_villager = true
				wolf = true
				lightning_bolt = true
				axolotl = true
				witch = true
				tropical_fish = true
				boat = true
				salmon = true
				wandering_trader = true
				horse = true
				experience_bottle = true
				turtle = true
				iron_golem = true
				villager = true
				donkey = true
				ender_pearl = true
				pillager = true
				item_frame = true
				phantom = true
				small_fireball = true
				rabbit = true
				husk = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.graveyard]
				corrupted_vindicator = true
				corrupted_pillager = true
				acolyte = true
				ghoul = true
				skeleton_creeper = true
				wraith = true
				nightmare = true
				revenant = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true
				dead_beard = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				coconut_crab = true

			[light_sources.settings.entities.duckling]
				duck = true
				duck_egg = true

			[light_sources.settings.entities.wondrouswilds]
				firefly = true

			[light_sources.settings.entities.direbats]
				direbat = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.betternether]
				chair = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.charm]
				chair = true

			[light_sources.settings.entities.gobber2]
				gobber2_arrow = true

			[light_sources.settings.entities.hexal]

				[light_sources.settings.entities.hexal.wisp]
					wandering = true

