name: Zip and Upload via FTP

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install zip
      run: sudo apt-get install -y zip
    - name: Zip repository
      run: mkdir dist && zip -r dist/Koerbchen-Modpack.zip .
    - name: 📂 Upload File
      uses: tomasbkk/action-ftp-file-upload@v1.0
      with:
        src: Koerbchen-Modpack.zip
        dest: /Koerbchen-Modpack.zip
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
        remoteDir: "/"

  push_message:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish News!
        run: |
          DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_API_URL="https://discord.com/api/v9"
          CHANNEL_ID="1135590247770628177"
          MESSAGE="Wir haben soeben unser Modpack geupdated! Bitte lade die neuste Version runter: https://minecraft-assets.koerbchen.net/Koerbchen-Modpack.zip"

          curl -X POST -H "Authorization: Bot ${DISCORD_BOT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"${MESSAGE}\"}" \
            "${DISCORD_API_URL}/channels/${CHANNEL_ID}/messages"
