name: Zip and Upload via FTP

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install zip
      run: sudo apt-get install -y zip
    - name: Zip repository
      run: mkdir dist && zip -r dist/Koerbchen-Modpack.zip .
    - name: 📂 Upload File
      run: |
        sudo apt-get install -y lftp
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ftp:ssl-allow no; put -O / dist/Koerbchen-Modpack.zip; bye" ftp://${{ secrets.FTP_SERVER }}

  push_message:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish News!
        run: |
          DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_API_URL="https://discord.com/api/v9"
          CHANNEL_ID="1135590247770628177"
          MESSAGE="Wir haben soeben unser Modpack geupdated! Bitte lade die neuste Version runter: https://minecraft-assets.koerbchen.net/Koerbchen-Modpack.zip"

          curl -X POST -H "Authorization: Bot ${DISCORD_BOT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"${MESSAGE}\"}" \
            "${DISCORD_API_URL}/channels/${CHANNEL_ID}/messages"
